### ISSUE TITLE
Complex languages rendering support

### ISSUE THREAD

**Issue by anishsheela** [romgere/text2stl#100]
The complex rendering like Malayalam language is not supported.

**Comment by romgere** [comment]
Hi @anishsheela thx for reporting an issue. Can you explain a little bit more what is happening & provide a way to reproduce your issue (+ maybe a screenshot) ?

**Comment by anishsheela** [comment]
See this. The word 'Swathanthrayam' - സ്വാതന്ത്ര്യം in Malayalam language, which is rendered in the app.
<img width="1582" alt="Screenshot 2023-09-25 at 16 11 19" src="https://github.com/romgere/text2stl/assets/148794/0df7b8c7-80c0-46c3-9484-06a37cbc6079">

It is supposed to be rendered like this:
<img width="293" alt="Screenshot 2023-09-25 at 16 10 38" src="https://github.com/romgere/text2stl/assets/148794/ca6b0ec8-7dcb-46b5-a7ff-dc238a145911">

Use Languages -> Malayalam and Font Manjari for this.

If I get some pointers, I can raise a PR. I am currently clueless on how rendering works.

**Comment by anishsheela** [comment]
From the source code, I can see that you are rendering character by character. In Indian languages, we have compound characters, like ക്ക -> ക + ് + ക . So, that logic won't work for non-latin languages. Is there any pointers to fix this? If it is fixed, then it can render a lot of languages.

**Comment by romgere** [comment]
@anishsheela Thank you for those details, I now have a better understanding of the issue... That said, I'm not sure how to fix it. I'll work on it when time will allow...

**Comment by anishsheela** [comment]
Thanks for the effort. Seems like its an issue with opentype.js . Let me open an issue over there.

**Comment by romgere** [comment]
Thanks @anishsheela , in the Meanwhile I was wondering if I could get rid of opentype.js & get the text rendered by an HTML canvas 🤔 I'll try to see if it could work. If yes, I could get the text rendering done by the browser itself and not by a 3rd party lib, which could be nice...

I'll keep you posted on that.

**Comment by romgere** [comment]
Using HTML canvas is basically a dead-end, you just can't extract path from an existing canvas 😞

**Comment by romgere** [comment]
I did some test with [harfbuzzjs](https://github.com/harfbuzz/harfbuzzjs) and result seems to be correct :

@anishsheela can you confirm the "word 'Swathanthrayam' - സ്വാതന്ത്ര്യം"  is correctly rendered bellow : 
![image](https://github.com/romgere/text2stl/assets/13900970/e8fe7f45-8e9c-43ab-80b5-acaf9f92b195)

That's a good new and using `harfbuzzjs` instead of `opentype`should not be too much complicated. Maybe both implementation can cohabit together 🤔 


note: test done on https://harfbuzz.github.io/harfbuzzjs/ with this font : https://fonts.google.com/specimen/Manjari

**Comment by anishsheela** [comment]
Yes. It is rendered correctly.

**Comment by romgere** [comment]
Hey @anishsheela I have some good news for you : 
![image](https://github.com/romgere/text2stl/assets/13900970/d2010bc6-b380-403f-966b-1598f02845d9)

I need to clean code & write some test, but it should land soon on production 😉

**Comment by romgere** [comment]
@anishsheela I'm please to announce that a fix has been deploy, it should be available soon on public URL 🎉
