### ISSUE TITLE
Settings resolution

### ISSUE THREAD

**Issue by dckaminski** [romgere/text2stl#121]
Settings on the text2stl web site can currently be modified in 1 mm increments.  Would it be possible to modify the settings to allow for 0.1 mm increments?

I am using the web site to create name plaques for a 3D printer. The letters of the name are "dot-matrix" blocks created from the characters of a text string (either the same text string as the larger text, or another text string).  Being able to adjust the settings in smaller increments would allow additional fine tuning in moving the individual small characters together to form a 3D-printable block of text.

Thank you for any help or ideas you can provide.
![David_3d_blue](https://github.com/romgere/text2stl/assets/68273530/7f99771c-eccb-414e-b97b-c5d13bf2e3a7)

**Comment by flyingcheesehead** [comment]
Yes! I'm currently attempting to make a 3mm thick nameplate to go inside another 3d print and I would like to do it in two 1.5mm thick layers (one black with a "hole" of the text, and one white with positive text).

https://www.thingiverse.com/thing:3082572

**Comment by romgere** [comment]
@flyingcheesehead  I worked on this recently, can you give the new feature a try : https://deploy-preview-128--text2stl.netlify.app/

You can now enter decimal number into all settings fields : 
![image](https://github.com/romgere/text2stl/assets/13900970/bc02f8b3-bb03-4da7-a70b-53c094610ef2)

**Comment by romgere** [comment]
Done & available in production (or will be available shortly)
