### ISSUE TITLE
Option to export via OBJ or FBX

### ISSUE THREAD

**Issue by MrolivesGaming** [romgere/text2stl#122]
i like to use this tool for making text models for my video games, however i usually have to convert said file to fbx in order to import it.
it would be nice if this tool had a native fbx option.

**Comment by romgere** [comment]
Hi @MrolivesGaming, the tool is using three.js under the hood, so OBJ export should be easy to implement, but there's no FBX exporter at the moment.

I'm adding this on my to-do list and will try to add this feature when time will allow me to do it.

**Comment by MrolivesGaming** [comment]
luckly a new update came out on my game development platform allowing obj file uploads, OBJ will work great!

**Comment by romgere** [comment]
@MrolivesGaming I worked on this recently, can you give the new feature a try : https://deploy-preview-127--text2stl.netlify.app/

Export button now allow you to choose file format : 
![image](https://github.com/romgere/text2stl/assets/13900970/7cea42b3-9369-4dd7-844c-02e48e813dbd)
