### ISSUE TITLE
Multi-Color printing suggestion

### ISSUE THREAD

**Issue by Gryzounours** [romgere/text2stl#126]
Bonjour,
il pourrait être intéressant d'ajouter la possibilité d'exporter l'impression multi-couleur notamment pour les imprimantes bambulab.

https://makerworld.com/en/models/16343#profileId-15224

Ca ressemble à ça

Merci

**Comment by romgere** [comment]
Bonjour, 

il n'est pas prévu pour le moment d'ajouter le support pour générer des fichiers 3mf avec cet outils.

Les modèles 3D générés étant assez simple pour une impression multi-couleur manuelle (changement de couleur à une certaine couche/hauteur).

C'est d'ailleurs ce qui est suggérer dans le lien que tu évoques :
 
![image](https://github.com/romgere/text2stl/assets/13900970/99aef216-4ed6-4070-9879-aa9cb2148428)


==============================================

I have no plan to add 3MF file support to the tool for now.

2 reasons : 
- 3D model generated are basic enough to do manual multi-color printing (adding filament change after layer/height)
- three.js library (used by this tool) does not provide 3MF converter.
