### ISSUE TITLE
Feature request: multiline support

### ISSUE THREAD

**Issue by jarirajari** [romgere/text2stl#33]
Hi, nice job! Noticed that multi-line support is on the TODO list, but thought that I give it +1 to help on prioritizing :)

**Comment by romgere** [comment]
Thx for your feedback @jarirajari. I'll keep this in mind when time will allow to work on this tool.
Also if you want & have time, don't hesitate to contribute ;)

**Comment by romgere** [comment]
Hey, @jarirajari I finaly found some time earlier than expected : 
![image](https://user-images.githubusercontent.com/13900970/152387120-35f2205f-fd96-43a8-b54a-ea55daf97e8d.png)
It should be available on public URL soon...

Feel free to test & open issue if you find any bug& don't hesitate to share this tool ;)

**Comment by jarirajari** [comment]
Cool. Thank you! Next stop is at a 3D printer! Already shared in Twitter...
