### ISSUE TITLE
Request Fonts

### ISSUE THREAD

**Issue by chouw2** [romgere/text2stl#43]
Hi
Can you put Star Wars Fonts?
and/or any popular publicity or tv, or movie etc.
please!

**Comment by romgere** [comment]
Hi @chouw2 thanks for you request. For now available fonts comes from google font & so I can't any font to the collection.

But one of the feature I plan to work on is the ability to upload custom font, so you'll be able to use the font you want.

I keep this issue open & will ping you when time will allow me to work on this feature.

**Comment by romgere** [comment]
Hey @chouw2 good new ! I found some time to work on the custom font feature.

You're now able to select a font file from your computer : 
![custom_font](https://user-images.githubusercontent.com/13900970/162421652-49b0322d-6ab6-49fd-8a4d-46b2d8a6f08d.gif)

(You should be able to find some Star Wars or whatever font on internet & use it in the tool)

Enjoy
