### ISSUE TITLE
custom font won't upload

### ISSUE THREAD

**Issue by sitoko** [romgere/text2stl#52]
Tried it with .ttf and .otf files. I always get this message:
Unsupported font file type, please use .woff, .otf or .ttf file.

Chrome and Edge.

**Comment by romgere** [comment]
Hi @sitoko it seems to work on my side (Chrome) : 
![image](https://user-images.githubusercontent.com/13900970/181448517-e449f64f-6bca-4b74-953b-15bab77d94c5.png)

Can you provide the font you're trying to use 🙏🏻

**Comment by sitoko** [comment]
The font is called rastanty cortez

**Comment by romgere** [comment]
I can use the rastanty cortez font wihout issue here : 
![image](https://user-images.githubusercontent.com/13900970/181477882-412580d0-8f27-415f-8450-f28c276e63a1.png)

Downloaded from https://www.dfonts.org/fonts/rastanty-cortez/

**Comment by sitoko** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/100168061/181495203-209cee8d-f48c-40cd-83ac-d4d8dded2426.png">

Ok, seems to be my notebook, I'll let you know if I can find the reason. It is working with my smartphone.
Thank you for this awesome tool!
