### ISSUE TITLE
unable to use a custom font

### ISSUE THREAD

**Issue by Asssticot** [romgere/text2stl#55]
Hi, is there any requirement for the .otf files required? I'm using a .otf downloaded from dafont but it looks like it's not recognized as a compatible font. The font is Belle Allure (https://www.dafont.com/fr/search.php?q=belle+allure). I tried with firefox on windows and chrome + safari on a mac.

**Comment by romgere** [comment]
Hi @Asssticot, Not sure what's going on here... otf files seems ok as there's no error, but the text can't be rendered by the app...
I will dig into this issue when time will allow.

**Comment by mort12r1** [comment]
I'm unable to use a custom font. I've tried both TTF and OTF versions of the same font, using Chrome on a Chromebook and Edge on a Windows machine.
My boss, however, had no problems using a custom font using Chrome on a MacBook. I'm not entirely sure what's going on here.

**Comment by romgere** [comment]
@mort12r1 thanks for reporting the issue, can you explain a little bit more ? Do you have an error ?
Can you try to open chrome devtool (hit F12), reproduce the issue & tell me if you're seing any error int the console ?

**Comment by romgere** [comment]
Oh actually I think I can reproduce the issue, no text is rendered when I'm using the font 🎉 (First time I can reproduce a font issue).
I'll investigate on it.

**Comment by norabbit28** [comment]
was this issue fixed? i have the  same problem

**Comment by romgere** [comment]
Hi there, the issue should now be fixed (please wait couple of minute before new version is being deployed)

I tested both font mentioned in this issue & both works.

@Asssticot, @mort12r1 & @norabbit28 feel free to reopen the issue if there's still an issue

Sorry for the delay, I was quite busy these weeks & issue wasn't easy to fix.

**Comment by norabbit28** [comment]
still, can't upload downloaded fonts even if it has the required file type

**Comment by romgere** [comment]
Thx @norabbit28 I found a Windows computer & managed to reproduce the issue. I'm re opening it & will try to work on a fix soon.

**Comment by romgere** [comment]
@norabbit28 the fix was easier than expected 😅 (at least the one about using Belle Allure (https://www.dafont.com/fr/search.php?q=belle+allure)

The issue was due to bad "mime type" on font file.

This is now fix & the app won't prevent you to load the font.

If you're still encountered issue, please create a new issue with the related file & info about browser / OS.

I won't reopen this issue as the initial issue was only about Belle Allure font.

**Comment by MayconFlavio** [comment]
Fixed! Thanks, God bless you! 

![imagem_2023-03-11_164934093](https://user-images.githubusercontent.com/127351051/224510989-a80e7b17-31c2-4507-a79b-01f65f258fdf.png)
