### ISSUE TITLE
Letter J is getting submerged in the support 

### ISSUE THREAD

**Issue by sanjus-robotic-studio** [romgere/text2stl#57]
The letter J is getting submerged in the support block. I am attaching the screenshot here.
![text to stl bug](https://user-images.githubusercontent.com/58104863/184370048-dd2625d1-27ea-4051-8bbf-9b811ffb30e1.PNG)

**Comment by romgere** [comment]
I'm not sure this is an issue 🤔 I mean, this is how the font should be align...
Maybe it worth to think about a new option to vertically align the text for the "vertical text with support" shape.
I need to check how it could be achieve.

**Comment by romgere** [comment]
This has been address some time ago with vertical alignment option : 
![image](https://github.com/romgere/text2stl/assets/13900970/a9957b1b-4ab3-49bf-bc93-d02d4ff0b83a)
![image](https://github.com/romgere/text2stl/assets/13900970/da509e7f-547f-4bed-89b2-c714e2e5857b)
