### ISSUE TITLE
Unable to upload custom font

### ISSUE THREAD

**Issue by d3rsch0rsch** [romgere/text2stl#59]
No matter the format (ttf, otf woff) i always receive "Unsupported font file type" message.

**Comment by romgere** [comment]
No issue found on current version 🤔 
![image](https://user-images.githubusercontent.com/13900970/188848922-9b9756ef-ae4f-49d7-904a-725f8230d825.png)


@d3rsch0rsch can you provide the font files you're using ?

Maybe related to #52 or #55 (specifics to the font)...

**Comment by d3rsch0rsch** [comment]
Different fonts from different sources.
[example fonts.zip](https://github.com/romgere/text2stl/files/9505021/example.fonts.zip)

**Comment by romgere** [comment]
Hum all of them works on my computer/browser : 

![image](https://user-images.githubusercontent.com/13900970/189066887-bebc8679-fe2c-47ea-99fe-d76610333f78.png)
![image](https://user-images.githubusercontent.com/13900970/189066927-24a81a8a-44ab-443c-b567-2b19792a019c.png)
![image](https://user-images.githubusercontent.com/13900970/189066970-49c29a10-0b95-4abf-9cc2-d0d5c114aa7b.png)

Can you give me more details about your OS / Browser.
Also, if you are familiar with browser dev tool, can you provide the console output.

Thx.

**Comment by romgere** [comment]
@d3rsch0rsch can I close the issue ?

**Comment by d3rsch0rsch** [comment]
Yep, sorry. Probably a local Problem. It works with my Android device.

**Comment by d3rsch0rsch** [comment]
Local problem
