### ISSUE TITLE
Cannot use certain fonts

### ISSUE THREAD

**Issue by crosejr** [romgere/text2stl#70]
Several fonts will not load as you get an error.

**Comment by romgere** [comment]
Thx @crosejr for reporting the issue. The library I used for loading font is no longer sync with the one use to display/select...

I'll work on a fix soon...

For now I did a quick fix to prevent the whole app to crash when a font can't be load.

**Comment by romgere** [comment]
@crosejr this is now fix, feel free to re-open this issue in case you still encountered issue
