### ISSUE TITLE
Cannot import custom font

### ISSUE THREAD

**Issue by Gryzounours** [romgere/text2stl#81]
Hello, I would like to import a custom font: https://freefonts.co/fonts/astoria-classic-sans-medium

Unfortunately, I get an unsupported font error message when I try to import it.

any idea ?

thanks

**Comment by romgere** [comment]
Hi @Gryzounours 

I successfully import that font on my computer (Mac OS & Chrome) : 
![image](https://user-images.githubusercontent.com/13900970/223053735-988a648a-52d5-43ee-b3bc-ee612435cd1c.png)


Can you tell me more about : 
- your browser version
- your OS
- The error message (if possible, please open "developper panel" before importing the font, by pressing F12 when on the browser & make a screenshot of the error).

**Comment by Gryzounours** [comment]
Hello,
-Chrome latest version
-Windows 10 with latest updates
![chrome_vjsFimxSyJ](https://user-images.githubusercontent.com/20440683/223213769-f73480c1-39a4-4c38-ac5a-eca352159464.png)

-

**Comment by romgere** [comment]
Thx @Gryzounours unfortunately there's no error in the console here (it has been catch by the app).
I updated the app to output the error in the console.
Can you give a ne try & make a new screen shot of the error message & the console please 🙏🏻

**Comment by romgere** [comment]
@Gryzounours a fix was made about some font loading issue (https://github.com/romgere/text2stl/issues/55).
Can you tell me if your issue is now solved ?

**Comment by Gryzounours** [comment]
Hello, 
Oui merci c'est bon ;)
