### ISSUE TITLE
is possible import another font downloaded on web?

### ISSUE THREAD

**Issue by MayconFlavio** [romgere/text2stl#87]
I tried convert font file to anothers formats, woff. woff2., .otf., ttf.
Tried upload another fonts too, but whithout success. Can anyone help me?

I need upload font (JK Abode Regular Demo) for a project in 3D model. 

![ERROR](https://user-images.githubusercontent.com/127351051/223851397-9a92207c-46d5-43f3-ae72-e1bddbfbe5df.png)
![FILES](https://user-images.githubusercontent.com/127351051/223851401-347630fc-e094-434a-b77f-df32aa495580.png)

**Comment by romgere** [comment]
Hi @MayconFlavio, I don't have issue using the "JK Abode Regular Demo" font downloaded from https://fonts2u.com/jk-abode-demo.font :

![image](https://user-images.githubusercontent.com/13900970/224008854-43660795-aeb5-485d-9073-6b0a576ed0fe.png)

There's maybe an issue when using Chrome on Windows (see #81) can you try to please open "developper panel" before importing the font, by pressing F12 when on the browser & make a screenshot of the error in the "console" tab.

I don't have any Windows computer to reproduce the issue.

Also, what you can try is to use Firefox, maybe it'll solve your issue 🤷🏻‍♂️

**Comment by romgere** [comment]
@MayconFlavio a fix was made about some font loading issue (#55) you should now be able to load your file without any issue...
