### ISSUE TITLE
Emoji / icon in text

### ISSUE THREAD

**Issue by demoniactaz08** [romgere/text2stl#90]
Bonjour
votre logiciel est très bien conçus, mais serrait-il possible d'intégré des objets, comme un cœur
merci

**Comment by romgere** [comment]
Bonjour @demoniactaz08, c'est une des évolution envisagé mais malheureusement les polices Google ne permettent pas nativement l'insertion d'emoji ou de caractères spéciaux...

Cela rend l'ajout de cette fonctionnalité compliqué (bien que pas impossible)

J'essaierai de travailler sur le sujet dès que le temps me le permettra.

**Comment by romgere** [comment]
I did some "research" on that...

Maybe "Noto Emoji" font can be the way to go (https://fonts.google.com/noto/specimen/Noto+Color+Emoji). This font can be used with text2stl "natively" & produce some results :
![image](https://github.com/romgere/text2stl/assets/13900970/daa47f1f-6345-41e0-8f1d-553074ed3259)


The tool could "automagically" use this font when emoji are detected in text 🤔 



That said some emoji are not correctly rendered.

Did quick test with `harfbuzzjs` & rendering version of emoji are looking really great:
![image](https://github.com/romgere/text2stl/assets/13900970/893bb429-03cd-47a7-b3b0-d9a69ddd229f)
![image](https://github.com/romgere/text2stl/assets/13900970/8f2fa3c0-a182-4ea6-ad1c-0be46d876e85)

**Comment by romgere** [comment]
@demoniactaz08 il est déjà possible d'utiliser la police "Noto Emoji" dans l'outil pour générer quelque Emoji, le rendu n'est pas parfais, mais c'est un début : 

![image](https://github.com/romgere/text2stl/assets/13900970/b0f3b90d-bf1c-4a63-8d51-176fe5e13c8b)
![image](https://github.com/romgere/text2stl/assets/13900970/8d847d48-2f49-4b53-b8a0-592e4c28a62e)
![image](https://github.com/romgere/text2stl/assets/13900970/e63b1b4f-9ef9-42fd-ba58-72c0103eeac6)


Attention, cependant il n'est pas (encore) possible de "mixer" Emoji & text.

**Comment by romgere** [comment]
This feature should be soon available 
![image](https://github.com/romgere/text2stl/assets/13900970/224c2b3f-59f8-4719-827f-ed1d51c63ff8)
