### ISSUE TITLE
Text2STL sinking the lower letters down the font support

### ISSUE THREAD

**Issue by karimsabi** [romgere/text2stl#92]
Hi
For the small letters like ( q  g j  p  y ), or some fonts and other languages, the letters will show sink down the support plate of the text.

Thanks and regards

**Comment by romgere** [comment]
I think this is duplicating #57 🤔 

> I'm not sure this is an issue 🤔 I mean, this is how the font should be align...
Maybe it worth to think about a new option to vertically align the text for the "vertical text with support" shape.
I need to check how it could be achieve.

I'm closing this one in favor or the #57
