### ISSUE TITLE
Persistent settings (perhaps url based?)

### ISSUE THREAD

**Issue by jenseng-form** [romgere/text2stl#96]
It would be great if you could configure the generator then come back to it later and have your settings still be there. Maybe a way to achieve this would be with URL parameters

**Comment by romgere** [comment]
Hi @jenseng-form, that's in the "roadmap" (my todo list) : 
![image](https://github.com/romgere/text2stl/assets/13900970/0ad50f7d-ea19-415e-af43-199fe52047d1)

That said, given it's a pet project, I can't give you any timeline on this.

**Comment by romgere** [comment]
@jenseng-form URL is now reflecting settings. You can bookmark URL to easily retrieve your settings (or use the save button & save the URL in the text area) : 

![image](https://github.com/romgere/text2stl/assets/13900970/06227750-4ad0-4d25-897b-01a28c4afdf9)

I'm closing this (you may have to wait a little bit before the feature being available in public URL).
