### ISSUE TITLE
Some of the handwriting fonts aren't being placed on top of the support

### ISSUE THREAD

**Issue by zephyr064** [romgere/text2stl#99]
Tried making a standing text of a name using handwriting font, specifically Alex Brush.

The font is not being placed on top of the support.  It's sort of burying part of the text.

<img width="559" alt="Screenshot 2023-08-14 at 10 57 30 PM" src="https://github.com/romgere/text2stl/assets/138292290/fe9fa957-0fe7-4da0-b031-07d72da574c8">

**Comment by romgere** [comment]
Hi @zephyr064 I added a "basic vertical alignement" feature to the tool, it's not perfect, but it should allow you to fix your issue :

BEFORE :
![image](https://github.com/romgere/text2stl/assets/13900970/ebbc6ec5-d31c-4012-8989-f817210eb3e9)


AFTER ("bottom" vertical text alignment) : 
![image](https://github.com/romgere/text2stl/assets/13900970/d421fcc3-a9c5-4574-9a33-401b0fa41fc5)

This will be available shortly on https://text2stl.mestres.fr/
